[package]
name = "monke_core"
version = "0.1.0"
edition = "2024"

[dependencies]
fnv = "1.0.7"
strum = "0.27.1"
strum_macros = "0.27.1"

[dev-dependencies]
criterion = { version = "0.7.0" }

[[bench]]
name = "benchmark"
harness = false
